name: Build RainCheck EXE

on:
push:
branches:
- main
workflow_dispatch:

jobs:
build:
runs-on: windows-latest

```
steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: 18

  - name: Setup Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.10'

  - name: Install frontend dependencies and build
    run: |
      cd frontend
      npm install
      npm run build

  - name: Install backend dependencies
    run: |
      cd backend
      pip install -r requirements.txt

  - name: Install electron dependencies
    run: |
      cd electron
      npm install
      npm install --save-dev electron-builder

  - name: Build Electron App (Windows EXE)
    run: |
      cd electron
      npx electron-builder --win

  - name: Upload EXE artifact
    uses: actions/upload-artifact@v4
    with:
      name: RainCheck-Installer
          path: electron/dist/*.exe
      path: electron/dist/*.exe
```
